# Generated by Django 6.0.7 on 2026-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='exercise',
            field=models.CharField(default='Nieznane', max_length=100),
        ),
    ]
