# Generated by Django 6.0.7 on 2026-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_trainingset_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='set_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Numer serii'),
        ),
    ]
