# Generated by Django 6.0.7 on 2026-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_trainingset_set_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data pomiaru')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Masa ciała (kg)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Spożyte kalorie (kcal)')),
                ('protein', models.PositiveIntegerField(blank=True, null=True, verbose_name='Białko (g)')),
                ('carbs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Węglowodany (g)')),
                ('fats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tłuszcze (g)')),
            ],
        ),
    ]
