# Generated by Django 6.0.7 on 2026-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_dailymetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa Ćwiczenia (Hevy)')),
                ('target_muscle', models.CharField(max_length=100, verbose_name='Partia mięśniowa')),
            ],
        ),
    ]
